package ru.kotikov.registry.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;registry_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.kotikov.registry.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.kotikov.registry.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee
 * @see ru.kotikov.registry.model.impl.EmployeeImpl
 * @see ru.kotikov.registry.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
     */

    /**
     * Returns the primary key of this employee.
     *
     * @return the primary key of this employee
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employee.
     *
     * @param primaryKey the primary key of this employee
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the employee ID of this employee.
     *
     * @return the employee ID of this employee
     */
    public long getEmployeeId();

    /**
     * Sets the employee ID of this employee.
     *
     * @param employeeId the employee ID of this employee
     */
    public void setEmployeeId(long employeeId);

    /**
     * Returns the last name of this employee.
     *
     * @return the last name of this employee
     */
    @AutoEscape
    public String getLastName();

    /**
     * Sets the last name of this employee.
     *
     * @param lastName the last name of this employee
     */
    public void setLastName(String lastName);

    /**
     * Returns the first name of this employee.
     *
     * @return the first name of this employee
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this employee.
     *
     * @param firstName the first name of this employee
     */
    public void setFirstName(String firstName);

    /**
     * Returns the patronymic of this employee.
     *
     * @return the patronymic of this employee
     */
    @AutoEscape
    public String getPatronymic();

    /**
     * Sets the patronymic of this employee.
     *
     * @param patronymic the patronymic of this employee
     */
    public void setPatronymic(String patronymic);

    /**
     * Returns the sex of this employee.
     *
     * @return the sex of this employee
     */
    @AutoEscape
    public String getSex();

    /**
     * Sets the sex of this employee.
     *
     * @param sex the sex of this employee
     */
    public void setSex(String sex);

    /**
     * Returns the date of birth of this employee.
     *
     * @return the date of birth of this employee
     */
    @AutoEscape
    public String getDateOfBirth();

    /**
     * Sets the date of birth of this employee.
     *
     * @param dateOfBirth the date of birth of this employee
     */
    public void setDateOfBirth(String dateOfBirth);

    /**
     * Returns the position ID of this employee.
     *
     * @return the position ID of this employee
     */
    public long getPositionId();

    /**
     * Sets the position ID of this employee.
     *
     * @param positionId the position ID of this employee
     */
    public void setPositionId(long positionId);

    /**
     * Returns the date of employment of this employee.
     *
     * @return the date of employment of this employee
     */
    @AutoEscape
    public String getDateOfEmployment();

    /**
     * Sets the date of employment of this employee.
     *
     * @param dateOfEmployment the date of employment of this employee
     */
    public void setDateOfEmployment(String dateOfEmployment);

    /**
     * Returns the salary of this employee.
     *
     * @return the salary of this employee
     */
    public int getSalary();

    /**
     * Sets the salary of this employee.
     *
     * @param salary the salary of this employee
     */
    public void setSalary(int salary);

    /**
     * Returns the work phone number of this employee.
     *
     * @return the work phone number of this employee
     */
    @AutoEscape
    public String getWorkPhoneNumber();

    /**
     * Sets the work phone number of this employee.
     *
     * @param workPhoneNumber the work phone number of this employee
     */
    public void setWorkPhoneNumber(String workPhoneNumber);

    /**
     * Returns the mobile phone number of this employee.
     *
     * @return the mobile phone number of this employee
     */
    @AutoEscape
    public String getMobilePhoneNumber();

    /**
     * Sets the mobile phone number of this employee.
     *
     * @param mobilePhoneNumber the mobile phone number of this employee
     */
    public void setMobilePhoneNumber(String mobilePhoneNumber);

    /**
     * Returns the bank ID of this employee.
     *
     * @return the bank ID of this employee
     */
    public long getBankId();

    /**
     * Sets the bank ID of this employee.
     *
     * @param bankId the bank ID of this employee
     */
    public void setBankId(long bankId);

    /**
     * Returns the archive status of this employee.
     *
     * @return the archive status of this employee
     */
    public boolean getArchiveStatus();

    /**
     * Returns <code>true</code> if this employee is archive status.
     *
     * @return <code>true</code> if this employee is archive status; <code>false</code> otherwise
     */
    public boolean isArchiveStatus();

    /**
     * Sets whether this employee is archive status.
     *
     * @param archiveStatus the archive status of this employee
     */
    public void setArchiveStatus(boolean archiveStatus);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.kotikov.registry.model.Employee employee);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.kotikov.registry.model.Employee> toCacheModel();

    @Override
    public ru.kotikov.registry.model.Employee toEscapedModel();

    @Override
    public ru.kotikov.registry.model.Employee toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
