package ru.kotikov.registry.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;registry_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.kotikov.registry.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.kotikov.registry.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee
 * @see ru.kotikov.registry.model.impl.EmployeeImpl
 * @see ru.kotikov.registry.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
     */

    /**
     * Returns the primary key of this employee.
     *
     * @return the primary key of this employee
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employee.
     *
     * @param primaryKey the primary key of this employee
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the employee_id of this employee.
     *
     * @return the employee_id of this employee
     */
    public long getEmployee_id();

    /**
     * Sets the employee_id of this employee.
     *
     * @param employee_id the employee_id of this employee
     */
    public void setEmployee_id(long employee_id);

    /**
     * Returns the last_name of this employee.
     *
     * @return the last_name of this employee
     */
    @AutoEscape
    public String getLast_name();

    /**
     * Sets the last_name of this employee.
     *
     * @param last_name the last_name of this employee
     */
    public void setLast_name(String last_name);

    /**
     * Returns the first_name of this employee.
     *
     * @return the first_name of this employee
     */
    @AutoEscape
    public String getFirst_name();

    /**
     * Sets the first_name of this employee.
     *
     * @param first_name the first_name of this employee
     */
    public void setFirst_name(String first_name);

    /**
     * Returns the patronymic of this employee.
     *
     * @return the patronymic of this employee
     */
    @AutoEscape
    public String getPatronymic();

    /**
     * Sets the patronymic of this employee.
     *
     * @param patronymic the patronymic of this employee
     */
    public void setPatronymic(String patronymic);

    /**
     * Returns the sex of this employee.
     *
     * @return the sex of this employee
     */
    @AutoEscape
    public String getSex();

    /**
     * Sets the sex of this employee.
     *
     * @param sex the sex of this employee
     */
    public void setSex(String sex);

    /**
     * Returns the date_of_birth of this employee.
     *
     * @return the date_of_birth of this employee
     */
    @AutoEscape
    public String getDate_of_birth();

    /**
     * Sets the date_of_birth of this employee.
     *
     * @param date_of_birth the date_of_birth of this employee
     */
    public void setDate_of_birth(String date_of_birth);

    /**
     * Returns the position_id of this employee.
     *
     * @return the position_id of this employee
     */
    public long getPosition_id();

    /**
     * Sets the position_id of this employee.
     *
     * @param position_id the position_id of this employee
     */
    public void setPosition_id(long position_id);

    /**
     * Returns the date_of_employment of this employee.
     *
     * @return the date_of_employment of this employee
     */
    @AutoEscape
    public String getDate_of_employment();

    /**
     * Sets the date_of_employment of this employee.
     *
     * @param date_of_employment the date_of_employment of this employee
     */
    public void setDate_of_employment(String date_of_employment);

    /**
     * Returns the salary of this employee.
     *
     * @return the salary of this employee
     */
    public int getSalary();

    /**
     * Sets the salary of this employee.
     *
     * @param salary the salary of this employee
     */
    public void setSalary(int salary);

    /**
     * Returns the work_phone_number of this employee.
     *
     * @return the work_phone_number of this employee
     */
    @AutoEscape
    public String getWork_phone_number();

    /**
     * Sets the work_phone_number of this employee.
     *
     * @param work_phone_number the work_phone_number of this employee
     */
    public void setWork_phone_number(String work_phone_number);

    /**
     * Returns the mobile_phone_number of this employee.
     *
     * @return the mobile_phone_number of this employee
     */
    @AutoEscape
    public String getMobile_phone_number();

    /**
     * Sets the mobile_phone_number of this employee.
     *
     * @param mobile_phone_number the mobile_phone_number of this employee
     */
    public void setMobile_phone_number(String mobile_phone_number);

    /**
     * Returns the bank_id of this employee.
     *
     * @return the bank_id of this employee
     */
    public long getBank_id();

    /**
     * Sets the bank_id of this employee.
     *
     * @param bank_id the bank_id of this employee
     */
    public void setBank_id(long bank_id);

    /**
     * Returns the archive_status of this employee.
     *
     * @return the archive_status of this employee
     */
    public boolean getArchive_status();

    /**
     * Returns <code>true</code> if this employee is archive_status.
     *
     * @return <code>true</code> if this employee is archive_status; <code>false</code> otherwise
     */
    public boolean isArchive_status();

    /**
     * Sets whether this employee is archive_status.
     *
     * @param archive_status the archive_status of this employee
     */
    public void setArchive_status(boolean archive_status);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.kotikov.registry.model.Employee employee);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.kotikov.registry.model.Employee> toCacheModel();

    @Override
    public ru.kotikov.registry.model.Employee toEscapedModel();

    @Override
    public ru.kotikov.registry.model.Employee toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
